### ISSUE TITLE
Rename the project

### ISSUE THREAD

**Issue by cgt** [remogatto/mandala#1]
Few are going to take this project seriously with that name. You really should consider calling it something else.

**Comment by beardedninja** [comment]
+1

**Comment by xyproto** [comment]
+1

**Comment by shoenig** [comment]
+1

**Comment by bbalet** [comment]
+1

**Comment by mchiodo** [comment]
+1

**Comment by pib** [comment]
+1 for gorgonzola

**Comment by kellydunn** [comment]
+1

**Comment by jordan-wright** [comment]
+1

**Comment by remogatto** [comment]
I wrote this software for the community and if the community has a problem using it because of its name, I'll just rename it. I think this is coherent with my original aim (give something to the community and, in case, receive feedback and contributions from it). So, I'll do that without regret.

If you like, you can stop reading here, nothing fundamental follows.

However, the [public announcement](https://groups.google.com/d/msg/golang-nuts/_b5penU7l5Y/AjIpq8FEP4UJ) of Gorgasm turned into an interesting and totally unintended social experiment. I'd like to share some considerations about it, with the community itself.

First of all, I realized clearly how much I'm lucky. I'm lucky because in my work I'm free. I had this feeling reading some of the comments appeared on [reddit](http://redd.it/1v0ys5) and [Google+](https://plus.google.com/100271912081202470197/posts/SewENgKMhkQ). I write software for fun. It's my passion, it's the channel through which I express my creativity. It's not my main work, actually. Sure, I can make money from it but, luckly, I have no bosses and I can give to my creations the labels I want. I can use the technologies I want (whatever are their names). I can play with code as much as I want, I can produce totally useless piece of code just for the sake of experimenting. In short, I'm free to choice.

My second consideration is about judgement. I learned a lesson some time ago about judgement versus opinion and I'm happy to share it with you.

If I look at a picture and I say «That picture _is_ gross» I'm emitting a judgement because I'm supposing that my idea about the picture _define_ the picture itself. In other words, I'm giving an _absolute value_ to my idea. But if I look at the same picture and I say «In my opinion that picture has garish colors that hurt my sensibility» I'm emitting a personal, respectable opinion. That picture looks _to me_ that way but this has nothing to do with the _intrinsic value_ of what I'm seeing. I think that in human relationship judgement vs opinion makes the difference. My idea is that judgement doesn't penalize the object, which preserves the intrinsic qualities. I think it penalizes the judging subject, conditioning his/herself against the object of his/her observation. I think that this behavior is _non-functional_ because it limits our knowledge of the others and of the world. Since I learnt this lesson, I try to avoid judgement and I live much better.

Now, let's go back to code.

**Comment by dreamfall** [comment]
Well, I don't want to dissapoint you, buy the new project name sounds awesome for russians now! :D

http://translate.google.com/#ru/en/%D0%BC%D0%B0%D0%BD%D0%B4%D0%B0

**Comment by kachayev** [comment]
+1 to change current name (mandala). It's event worse then previous one from the point of russian-speaking developer.

**Comment by cgt** [comment]
Many combinations of letters mean something offensive in some language(s). English is the de facto lingua franca of computers, so as long as it isn't offensive in English, that should be good enough. It certainly is unfortunate if it has an offensive meaning in another language—especially if it is a language with as many speakers as Russian—but it is simply impractical to make sure that it has no offensive meaning in any language.

**Comment by dominikh** [comment]
MongoDB did fine, despite Mongo loosely translating to "retard" in German.

**Comment by dreamfall** [comment]
> MongoDB did fine, despite Mongo loosely translating to "retard" in German.

Thanks! That explains a lot! :D

**Comment by dansouza** [comment]
> MongoDB did fine, despite Mongo loosely translating to "retard" in German.

And in Portuguese too, mongo/mongol is a slang for "retard" !

**Comment by pierrre** [comment]
What do you think of "gonorrhea"?

**Comment by bbalet** [comment]
In france, a car constructor was forced to withdraw a model called eTron
because it litteraly means "piece of shit" and they sold not a single one...
Just my useless contribution to the community.

**Comment by cjthomp** [comment]
English actually uses (well, used; it's uncommon now) "mongoloid" in the same way. "Mongo" is still a nickname that implies a person is "developmentally challenged."

**Comment by xyproto** [comment]
As an apropos, Toyota Fitta was launched in Norway, then retracted. Fitta means cunt.
